version: "3"

services:
  bot:
    container_name: bolb-bot
    env_file: .env
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/bot/logs
      - sqlite:/bot/db

volumes:
  sqlite:
